# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4cecedb4924bebbac251ba8d425f648a9626054b21933ea456db54b5e51d8a353385a32bb43fdd9a377a6156e5d2cb33f9ed7253d0104aef27e47dc6d359d791

test:
  secret_key_base: 556effd9d7ed1c404ce8737acb8c108e1e953764818923d5b9643e35ee3e4c2cdbc47f1973757f5078a2c4d34a396ccc6bc84a7d4b960a0b8cff7c04e0236f9e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
